In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
automobile = pd.read_csv('datasets/CarPrice_Assignment.csv')
automobile.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [4]:
automobile.shape

(205, 26)

In [5]:
automobile.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [6]:
automobile.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [7]:
automobile = pd.get_dummies(automobile)

In [8]:
automobile.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [9]:
automobile.shape

(205, 52)

In [10]:
X = automobile.drop('price', axis=1)
Y = automobile['price']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [12]:
x_train.shape, x_test.shape

((164, 51), (41, 51))

In [13]:
y_train.shape, y_test.shape

((164,), (41,))

In [14]:
model = LinearRegression().fit(x_train, y_train)

In [15]:
training_score = model.score(x_train, y_train)
training_score

0.9468400343609742

In [16]:
y_pred = model.predict(x_test)
y_pred

array([15724.53431783,  7423.46886304, 14325.14772699,  6368.94424017,
       37481.28529122, 10674.78973395,  8505.88806755, 28213.83113361,
        9945.27663227, 10327.73998738, 19950.03322417, 31529.62290178,
       20730.21382128, 16518.89385845,  6533.34736372, 12948.8881793 ,
        7789.55676887, 17292.77400975,  6203.09859293, 26405.73659778,
        6134.000475  ,  7599.15033141,  6473.40994381, 13297.14106088,
        8283.53458202,  7580.6468526 , 20364.21744623, 20194.19536786,
        6224.41406124, 14639.43811681, 11930.65411748, 11032.06771872,
       15694.40823353, 43229.99230017, 10044.08502511, 18044.38424268,
       38660.00682638,  9922.4179104 ,  9319.72493919, 18368.56753358,
       16999.58719573])

In [17]:
testing_score = r2_score(y_test, y_pred)
testing_score

0.8072686449519989

In [18]:
import json

In [19]:
model.coef_

array([-8.98455189e+00, -7.07738060e+01,  1.00680050e+03, -2.10549523e+01,
        5.56188803e+00,  9.96126399e+01, -2.64550288e+03, -3.41438135e+03,
       -1.03946143e+03, -1.57425507e+01,  2.99655884e+00,  6.49530259e+01,
        6.67444924e+00,  5.01364105e+03, -5.01364105e+03, -2.46617988e+02,
        2.46617988e+02, -1.76277459e+01,  1.76277459e+01,  3.94399156e+03,
       -9.02949286e+02, -1.42890540e+03, -2.35827269e+02, -1.37630961e+03,
       -9.36763563e+02, -7.68899246e+02,  1.70566281e+03, -2.93267473e+03,
        2.93267473e+03, -7.75023960e+02, -6.71083857e+03, -7.26916097e+01,
        5.56501501e+03,  5.05538440e+03, -5.02510517e+03,  1.96325989e+03,
        8.00178442e+03, -6.48108264e+03, -6.73864754e+03, -1.09507876e+03,
        4.34976462e+03,  0.00000000e+00,  1.96325989e+03, -3.61876168e+02,
        4.18523640e+02, -1.99273344e+03,  5.01364105e+03,  0.00000000e+00,
        4.53183158e+02, -1.80284463e+03, -1.72789360e+03])

In [20]:
model.intercept_

-42347.9476413064

In [21]:
model_param = {}

model_param['coef'] = list(model.coef_)
model_param['intercept'] = model.intercept_.tolist()

In [22]:
json_txt = json.dumps(model_param, indent=4)
json_txt

'{\n    "coef": [\n        -8.9845518945936,\n        -70.77380600848636,\n        1006.8004957750263,\n        -21.054952259660045,\n        5.561888029566973,\n        99.61263992615264,\n        -2645.5028757949767,\n        -3414.381352762374,\n        -1039.4614319388106,\n        -15.742550720418876,\n        2.9965588410559576,\n        64.95302588911272,\n        6.674449236599685,\n        5013.641047951991,\n        -5013.6410479519645,\n        -246.61798789390963,\n        246.61798789398438,\n        -17.627745875737077,\n        17.62774587574765,\n        3943.9915620323004,\n        -902.9492859181015,\n        -1428.9053974542005,\n        -235.82726868776268,\n        -1376.3096099720235,\n        -936.7635630743748,\n        -768.8992461960745,\n        1705.6628092703252,\n        -2932.67472849657,\n        2932.6747284965654,\n        -775.0239601255914,\n        -6710.8385665111355,\n        -72.6916097124404,\n        5565.015005593467,\n        5055.3844045652,

In [23]:
with open('models/regressor_param.txt', 'w') as file:
    file.write(json_txt)

In [24]:
with open('models/regressor_param.txt', 'r') as file:
    json_text = json.load(file)

In [25]:
json_model = LinearRegression()

In [26]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [27]:
y_pred = json_model.predict(x_test)
r2_score(y_test, y_pred)

0.8072686449519989

### Pickle

In [28]:
import pickle

In [29]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [30]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [32]:
y_pred = pickle_model.predict(x_test)
y_pred

array([15724.53431783,  7423.46886304, 14325.14772699,  6368.94424017,
       37481.28529122, 10674.78973395,  8505.88806755, 28213.83113361,
        9945.27663227, 10327.73998738, 19950.03322417, 31529.62290178,
       20730.21382128, 16518.89385845,  6533.34736372, 12948.8881793 ,
        7789.55676887, 17292.77400975,  6203.09859293, 26405.73659778,
        6134.000475  ,  7599.15033141,  6473.40994381, 13297.14106088,
        8283.53458202,  7580.6468526 , 20364.21744623, 20194.19536786,
        6224.41406124, 14639.43811681, 11930.65411748, 11032.06771872,
       15694.40823353, 43229.99230017, 10044.08502511, 18044.38424268,
       38660.00682638,  9922.4179104 ,  9319.72493919, 18368.56753358,
       16999.58719573])

In [33]:
r2_score(y_test, y_pred)

0.8072686449519989

In [34]:
testing_score

0.8072686449519989

### Joblib

In [35]:
import joblib

In [36]:
filename = 'models/model.joblib'

joblib.dump(model, filename)

['models/model.joblib']

In [37]:
joblib_model = joblib.load(filename)

In [38]:
y_pred = joblib_model.predict(x_test)
y_pred

array([15724.53431783,  7423.46886304, 14325.14772699,  6368.94424017,
       37481.28529122, 10674.78973395,  8505.88806755, 28213.83113361,
        9945.27663227, 10327.73998738, 19950.03322417, 31529.62290178,
       20730.21382128, 16518.89385845,  6533.34736372, 12948.8881793 ,
        7789.55676887, 17292.77400975,  6203.09859293, 26405.73659778,
        6134.000475  ,  7599.15033141,  6473.40994381, 13297.14106088,
        8283.53458202,  7580.6468526 , 20364.21744623, 20194.19536786,
        6224.41406124, 14639.43811681, 11930.65411748, 11032.06771872,
       15694.40823353, 43229.99230017, 10044.08502511, 18044.38424268,
       38660.00682638,  9922.4179104 ,  9319.72493919, 18368.56753358,
       16999.58719573])

In [39]:
r2_score(y_test, y_pred)

0.8072686449519989

In [40]:
testing_score

0.8072686449519989